// Dummy data for videos and series
export const mockVideos = [
  {
    id: 1,
    title: "How to Learn English Fast!",
    guide: "Jane Doe",
    link: "dQw4w9WgXcQ", // YouTube video ID
    level: "Beginner",
    accent: "US",
    topics: ["Speaking", "Listening"],
    locked: false,
  },
  {
    id: 2,
    title: "Mastering English Pronunciation",
    guide: "John Smith",
    link: "9bZkp7q19f0",
    level: "Intermediate",
    accent: "UK",
    topics: ["Pronunciation"],
    locked: true,
  },
  {
    id: 3,
    title: "English Idioms for Daily Life",
    guide: "Emily Clark",
    link: "3JZ_D3ELwOQ",
    level: "Advanced",
    accent: "AU",
    topics: ["Idioms", "Vocabulary"],
    locked: false,
  },
];

export const mockSeries = [
  {
    id: 1,
    title: "Business English Series",
    name: "Business English Series",
    guide: "Jane Doe",
    link: "dQw4w9WgXcQ",
    level: "Intermediate",
    accent: "US",
    topics: ["Business", "Meetings"],
    locked: false,
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    shortDescription: "Master business English for meetings and presentations.",
    description:
      "A series focused on English for business settings, including meetings, presentations, and negotiations.",
  },
  {
    id: 2,
    title: "Travel English Series",
    name: "Travel English Series",
    guide: "John Smith",
    link: "9bZkp7q19f0",
    level: "Beginner",
    accent: "UK",
    topics: ["Travel", "Culture"],
    locked: false,
    thumbnail: "https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg",
    shortDescription: "Essential English for travelers.",
    description:
      "Learn the basics of English for travel, including airport, hotel, and sightseeing conversations.",
  },
  {
    id: 3,
    title: "Everyday English Series",
    name: "Everyday English Series",
    guide: "Emily Clark",
    link: "3JZ_D3ELwOQ",
    level: "Beginner",
    accent: "AU",
    topics: ["Daily Life", "Conversation"],
    locked: false,
    thumbnail: "https://img.youtube.com/vi/3JZ_D3ELwOQ/hqdefault.jpg",
    shortDescription: "English for daily conversations.",
    description:
      "Improve your English for everyday situations like shopping, dining, and making friends.",
  },
  {
    id: 4,
    title: "Advanced Grammar Series",
    name: "Advanced Grammar Series",
    guide: "Michael Brown",
    link: "e-ORhEE9VVg",
    level: "Advanced",
    accent: "US",
    topics: ["Grammar", "Writing"],
    locked: true,
    thumbnail: "https://img.youtube.com/vi/e-ORhEE9VVg/hqdefault.jpg",
    shortDescription: "Take your grammar to the next level.",
    description:
      "Deep dive into advanced English grammar and writing skills for professionals and students.",
  },
  {
    id: 5,
    title: "Pronunciation Mastery",
    name: "Pronunciation Mastery",
    guide: "Sarah Lee",
    link: "L_jWHffIx5E",
    level: "Intermediate",
    accent: "UK",
    topics: ["Pronunciation", "Speaking"],
    locked: false,
    thumbnail: "https://img.youtube.com/vi/L_jWHffIx5E/hqdefault.jpg",
    shortDescription: "Perfect your English pronunciation.",
    description:
      "A series dedicated to mastering English pronunciation and speaking clearly in any situation.",
  },
];
